# wrangle(df)
# amenities_list = list(df.amenities)
# amenities_list_string = " ".join(amenities_list)
# # amenities_list_string = amenities_list_string.replace('{', '')
# # amenities_list_string = amenities_list_string.replace('}', ',')
# # amenities_list_string = amenities_list_string.replace('"', '')
# amenities_list_string = amenities_list_string.replace('\\', '')
# amenities_list_string = amenities_list_string.replace('u2013', '')
# amenities_list_string = amenities_list_string.replace('[', '')
# amenities_list_string = amenities_list_string.replace(']', '')
# amenities_list_string = amenities_list_string.replace(':', '')
# # amenities_list_string = amenities_list_string.replace('and', '')
# amenities_list_string = amenities_list_string.replace('amenities', '')
# amenities_list_string = amenities_list_string.replace(' In', 'in')
# # amenities_list_string = amenities_list_string.replace('-', '')
# # amenities_list_string = amenities_list_string.replace('  ', '')
# # amenities_set = [x.strip() for x in amenities_list_string.lower().split(',')]
# # amenities_set = set(amenities_set)


# amenities = [amenitie.replace('"','').strip() for amenitie in amenities_list_string.replace('{', '').replace('}', '').split(',')]
# set(amenities)

# # Check
# print(f"The dataset contains {len(df)} Airbnb listings\n")
# print(f'Amenities with TV: {len(df[df["amenities"].str.contains("TV")])}')
# print(f'Amenities with workspace: {len(df[df["amenities"].str.contains("workspace")])}')
# print(f'Amenities with Coffee: {len(df[df["amenities"].str.contains("Coffee")])}')
# print(f'Amenities with Bikes: {len(df[df["amenities"].str.contains("Bikes")])}')
# print(f'Amenities with Dishwasher: {len(df[df["amenities"].str.contains("Dishwasher")])}')
# print(f'Amenities with Breakfast: {len(df[df["amenities"].str.contains("Breakfast")])}')
# print(f'Amenities with Bidet: {len(df[df["amenities"].str.contains("Bidet")])}')
# print(f'Amenities with Crib: {len(df[df["amenities"].str.contains("Crib")])}')
# print(f'Amenities with Clothing: {len(df[df["amenities"].str.contains("Clothing")])}')
# print(f'Amenities with Free parking: {len(df[df["amenities"].str.contains("Free parking")])}')
# print(f'Amenities with driveway parking: {len(df[df["amenities"].str.contains("driveway parking")])}')
# print(f'Amenities with hot tub: {len(df[df["amenities"].str.contains("hot tub")])}')
# print(f'Amenities with tub: {len(df[df["amenities"].str.contains("tub")])}')
# print(f'Amenities with Children toys: {len(df[df["amenities"].str.contains("Children")])}')
# print(f'Amenities with Private backyard: {len(df[df["amenities"].str.contains("Private backyard")])}')
# print(f'Amenities with Courtyard: {len(df[df["amenities"].str.contains("Courtyard")])}')
# print(f'Amenities with gym: {len(df[df["amenities"].str.contains("gym")])}')
# print(f'Amenities with Gym: {len(df[df["amenities"].str.contains("Gym")])}')
# print(f'Amenities with Pool: {len(df[df["amenities"].str.contains("Pool")])}')
# print(f'Amenities with Pool table: {len(df[df["amenities"].str.contains("Pool table")])}')
# print(f'Amenities with wifi: {len(df[df["amenities"].str.contains("wifi")])}')
# print(f'Amenities with Wifi: {len(df[df["amenities"].str.contains("Wifi")])}')
# print(f'Amenities with the word amenities: {len(df[df["amenities"].str.contains("amenities")])}')
# print(f'Not included: {len(df[df["amenities"].str.contains("Not included")])}')